/**
 * exporter.js
 * Exports validated env data to various formats (JSON, shell export statements, dotenv)
 */

/**
 * Export env object to JSON string
 * @param {Object} env
 * @param {Object} options
 * @returns {string}
 */
function toJSON(env, options = {}) {
  const { pretty = true, mask = false } = options;
  const data = mask
    ? Object.fromEntries(
        Object.entries(env).map(([k, v]) => [
          k,
          require('./masker').maskValue(k, v)
        ])
      )
    : env;
  return JSON.stringify(data, null, pretty ? 2 : 0);
}

/**
 * Export env object to shell export statements
 * @param {Object} env
 * @returns {string}
 */
function toShell(env) {
  return Object.entries(env)
    .map(([k, v]) => {
      const escaped = String(v).replace(/'/g, "'\\''")
      return `export ${k}='${escaped}'`;
    })
    .join('\n');
}

/**
 * Export env object back to dotenv format
 * @param {Object} env
 * @param {Object} options
 * @returns {string}
 */
function toDotenv(env, options = {}) {
  const { header = true } = options;
  const lines = [];
  if (header) {
    lines.push(`# Generated by envguard on ${new Date().toISOString()}`);
    lines.push('');
  }
  for (const [k, v] of Object.entries(env)) {
    const val = String(v);
    const needsQuotes = val.includes(' ') || val.includes('#') || val === '';
    lines.push(needsQuotes ? `${k}="${val.replace(/"/g, '\\"')}"` : `${k}=${val}`);
  }
  return lines.join('\n');
}

/**
 * Main export function — dispatches to format-specific handler
 * @param {Object} env
 * @param {'json'|'shell'|'dotenv'} format
 * @param {Object} options
 * @returns {string}
 */
function exportEnv(env, format = 'dotenv', options = {}) {
  switch (format) {
    case 'json':   return toJSON(env, options);
    case 'shell':  return toShell(env);
    case 'dotenv': return toDotenv(env, options);
    default:
      throw new Error(`Unknown export format: "${format}". Use json, shell, or dotenv.`);
  }
}

module.exports = { exportEnv, toJSON, toShell, toDotenv };
