const { exportEnv, toJSON, toShell, toDotenv } = require('./exporter');

const sampleEnv = {
  APP_NAME: 'myapp',
  PORT: '3000',
  DB_PASSWORD: 'secret123',
  EMPTY_VAR: '',
  SPACED: 'hello world',
};

describe('toJSON', () => {
  test('produces pretty JSON by default', () => {
    const out = toJSON({ FOO: 'bar' });
    expect(out).toContain('\n');
    expect(JSON.parse(out)).toEqual({ FOO: 'bar' });
  });

  test('produces compact JSON when pretty=false', () => {
    const out = toJSON({ FOO: 'bar' }, { pretty: false });
    expect(out).toBe('{"FOO":"bar"}');
  });

  test('masks sensitive keys when mask=true', () => {
    const out = toJSON({ DB_PASSWORD: 'secret' }, { mask: true });
    const parsed = JSON.parse(out);
    expect(parsed.DB_PASSWORD).not.toBe('secret');
  });
});

describe('toShell', () => {
  test('generates export statements', () => {
    const out = toShell({ FOO: 'bar', BAZ: '123' });
    expect(out).toContain("export FOO='bar'");
    expect(out).toContain("export BAZ='123'");
  });

  test('escapes single quotes in values', () => {
    const out = toShell({ MSG: "it's alive" });
    expect(out).toContain("it'\\''s alive");
  });
});

describe('toDotenv', () => {
  test('produces valid dotenv output', () => {
    const out = toDotenv({ FOO: 'bar' }, { header: false });
    expect(out).toBe('FOO=bar');
  });

  test('quotes values with spaces', () => {
    const out = toDotenv({ SPACED: 'hello world' }, { header: false });
    expect(out).toBe('SPACED="hello world"');
  });

  test('quotes empty values', () => {
    const out = toDotenv({ EMPTY: '' }, { header: false });
    expect(out).toBe('EMPTY=""');
  });

  test('includes header by default', () => {
    const out = toDotenv({ FOO: 'bar' });
    expect(out).toContain('# Generated by envguard');
  });
});

describe('exportEnv', () => {
  test('dispatches to json format', () => {
    const out = exportEnv({ FOO: 'bar' }, 'json');
    expect(() => JSON.parse(out)).not.toThrow();
  });

  test('dispatches to shell format', () => {
    const out = exportEnv({ FOO: 'bar' }, 'shell');
    expect(out).toContain('export FOO=');
  });

  test('dispatches to dotenv format', () => {
    const out = exportEnv({ FOO: 'bar' }, 'dotenv', { header: false });
    expect(out).toContain('FOO=bar');
  });

  test('throws on unknown format', () => {
    expect(() => exportEnv({}, 'xml')).toThrow('Unknown export format');
  });
});
